# Use root/example as user/password credentials
version: "3"

services:
  jenkins:
    image: wolffjose/jenkinsinstanceexamples:latest
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /tmp/jenkins_data:/var/jenkins_home
